#first run docker volume create --name=pgdata in terminal
version: '3'

services:

  # start Postgres, and ensure that data is stored to a mounted volume
  postgres:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: thelsblog
    volumes:
        - pgdata:/var/lib/postgresql/data


  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: always
      
volumes:
  pgdata:
    external: true